// Component type registry — single source of truth for all 12 component types.
// Matches _PART_REGISTRY in keyboardgenerator/keyboard.py exactly.

export const COMPONENTS = {
  cherry: {
    smValue: 'cherry',
    displayName: 'Cherry MX Key',
    abbrev: 'MX',
    category: 'Keys',
    defaultW: 1,
    defaultH: 1,
    defaultR: 0,
    color2d: '#4A90D9',
    color3d: 0x4A90D9,
    layer: 'all',
    hasTextProp: false,
    tip: 'Standard Cherry MX hotswap switch (19×19 mm footprint)',
  },
  kailhchoc: {
    smValue: 'kailhchoc',
    displayName: 'Kailh Choc Key',
    abbrev: 'CHOC',
    category: 'Keys',
    defaultW: 1,
    defaultH: 1,
    defaultR: 0,
    color2d: '#2471A3',
    color3d: 0x2471A3,
    layer: 'all',
    hasTextProp: false,
    tip: 'Kailh low-profile switch (19×19 mm footprint)',
  },
  arduino: {
    smValue: 'arduino',
    displayName: 'Arduino Pro Micro',
    abbrev: 'ARD',
    category: 'Electronics',
    defaultW: 1,
    defaultH: 2,
    defaultR: 0,
    color2d: '#27AE60',
    color3d: 0x27AE60,
    layer: 'pcb',
    hasTextProp: false,
    tip: 'Arduino Pro Micro MCU (19×39 mm). Place at keyboard edge, use h:2 in KLE.',
  },
  trrs: {
    smValue: 'trrs',
    displayName: 'TRRS Jack',
    abbrev: 'TRRS',
    category: 'Electronics',
    defaultW: 0.5,
    defaultH: 1,
    defaultR: 90,
    color2d: '#E67E22',
    color3d: 0xE67E22,
    layer: 'pcb',
    hasTextProp: false,
    tip: 'TRRS 3.5 mm audio jack for split keyboard. Placed at edge, rotated 90°.',
  },
  pinplate: {
    smValue: 'pinplate',
    displayName: 'Pin: Plate ↔ PCB',
    abbrev: 'PP',
    category: 'Pins',
    defaultW: 0.5,
    defaultH: 0.5,
    defaultR: 0,
    color2d: '#8E44AD',
    color3d: 0x8E44AD,
    layer: 'plate+pcb',
    hasTextProp: false,
    tip: 'Screw post connecting the plate to the PCB layer.',
  },
  pinpcb: {
    smValue: 'pinpcb',
    displayName: 'Pin: PCB ↔ Bottom',
    abbrev: 'PC',
    category: 'Pins',
    defaultW: 0.5,
    defaultH: 0.5,
    defaultR: 0,
    color2d: '#9B59B6',
    color3d: 0x9B59B6,
    layer: 'pcb+bottom',
    hasTextProp: false,
    tip: 'Screw post connecting the PCB to the bottom layer.',
  },
  pinb2t: {
    smValue: 'pinb2t',
    displayName: 'Pin: Bottom ↔ Plate',
    abbrev: 'PB',
    category: 'Pins',
    defaultW: 0.5,
    defaultH: 0.5,
    defaultR: 0,
    color2d: '#6C3483',
    color3d: 0x6C3483,
    layer: 'bottom+plate',
    hasTextProp: false,
    tip: 'Screw post connecting the bottom directly to the plate (bypasses PCB).',
  },
  hole: {
    smValue: 'hole',
    displayName: 'Screw Hole',
    abbrev: 'HOLE',
    category: 'Other',
    defaultW: 1,
    defaultH: 1,
    defaultR: 0,
    color2d: '#7F8C8D',
    color3d: 0x7F8C8D,
    layer: 'pcb',
    hasTextProp: false,
    tip: 'Rectangular cutout in the PCB layer for passing wires or LEDs through.',
  },
  platetext: {
    smValue: 'platetext',
    displayName: 'Engraved Text',
    abbrev: 'TXT',
    category: 'Other',
    defaultW: 1,
    defaultH: 0.5,
    defaultR: 0,
    color2d: '#F39C12',
    color3d: 0xF39C12,
    layer: 'plate',
    hasTextProp: true,
    tip: 'Text engraved into the plate surface. Enter text in the "p" field.',
  },
  cameramount_selftap: {
    smValue: 'cameramount_selftap',
    displayName: 'Camera Mount (self-tap)',
    abbrev: 'CAM',
    category: 'Bottom',
    defaultW: 0.5,
    defaultH: 0.5,
    defaultR: 0,
    color2d: '#E74C3C',
    color3d: 0xE74C3C,
    layer: 'bottom',
    hasTextProp: false,
    tip: 'Camera arm mount boss on the bottom layer. Screw taps directly into plastic.',
  },
  cameramount_heatset: {
    smValue: 'cameramount_heatset',
    displayName: 'Camera Mount (heat-set)',
    abbrev: 'CAM+',
    category: 'Bottom',
    defaultW: 0.5,
    defaultH: 0.5,
    defaultR: 0,
    color2d: '#C0392B',
    color3d: 0xC0392B,
    layer: 'bottom',
    hasTextProp: false,
    tip: 'Camera arm mount boss with a heat-set brass insert hole.',
  },
  tiltleg: {
    smValue: 'tiltleg',
    displayName: 'Tilt Leg',
    abbrev: 'LEG',
    category: 'Bottom',
    defaultW: 0.5,
    defaultH: 0.5,
    defaultR: 0,
    color2d: '#1ABC9C',
    color3d: 0x1ABC9C,
    layer: 'bottom',
    hasTextProp: false,
    tip: 'Tilt leg on the bottom layer. Height is auto-calculated by the Python tool based on the camera mount position.',
  },
};

// sm value → type key lookup (e.g. 'cherry' → 'cherry', 'cameramount_selftap' → 'cameramount_selftap')
export const SM_TO_TYPE = {};
for (const [key, comp] of Object.entries(COMPONENTS)) {
  SM_TO_TYPE[comp.smValue] = key;
}

// Also register old-style label fallbacks (PinPcb, PinPlate, PB2T, Arduino, trrs)
const LABEL_FALLBACKS = {
  'Arduino': 'arduino',
  'arduino': 'arduino',
  'trrs': 'trrs',
  'PinPcb': 'pinpcb',
  'PinPlate': 'pinplate',
  'PPlate': 'pinplate',
  'PB2T': 'pinb2t',
  'Hole': 'hole',
  'Text': 'platetext',
  'Leg': 'tiltleg',
  'Mount': 'cameramount_selftap',
};
export { LABEL_FALLBACKS };

export const CATEGORIES = ['Keys', 'Electronics', 'Pins', 'Bottom', 'Other'];

// Physical spacing constants (mm)
export const CHERRY_MX_SPACING = 19.05; // mm per key unit
export const LAYER_THICKNESS = 2.16;    // mm per layer
export const CHERRY_MX_HOLE = 14.03;   // mm hole size
